import React, { Component } from "react";
import { NavLink } from "react-router-dom";
import Nav from "./Nav";
import Loader from "./Loader";
import QuickLinks from "./QuickLinks";
import NavList from "./NavList";

export default class Terms extends Component {
  render() {
    return (
      <main>
        <Loader />
        <Nav />

        <div
          className="page-title-area item-bg2 jarallax"
          data-jarallax='{"speed": 0.3}'
        >
          <div className="container">
            <div className="page-title-content">
              <h2>Terms and conditions</h2>
            </div>
          </div>
        </div>

        {/* Start Blog Details Area  */}
        <section className="blog-details-area ptb-70">
          <div className="container">
            <div className="row">
              <div className="col-lg-12 col-md-12">
                <div className="blog-details">
                  <div className="article-content">
                    <p>
                      This document is an electronic record in terms of
                      Information Technology Act, 2000 and rules there under as
                      applicable and the amended provisions pertaining to
                      electronic records in various statutes as amended by the
                      Information Technology Act, 2000. This electronic record
                      is generated by a computer system and does not require any
                      physical or digital signatures.
                    </p>

                    <p>
                      These terms and conditions under this agreement ("
                      <strong>User Terms</strong>") apply on the usage of our
                      website www.dobzin.in ("<strong>Website</strong>"),
                      Service and to all information, recommendations and/or
                      services provided to you on or through the Website and/or
                      through the Customer Care ("<strong>CC</strong>") at{" "}
                      <a href="mailto:support@dobzin.in">support@dobzin.in</a>.
                    </p>

                    <p>
                      The terms and conditions mentioned in this contract along
                      with the Privacy Policy constitute the entire contract
                      between the User (as defined below) and Dobzin (as defined
                      below) with respect to access to and use of the website
                      and the Services (as defined below) offered by Dobzin,
                      superseding any prior written or oral contracts in
                      relation to the same subject matter herein.
                    </p>

                    <p>
                      The term "<strong>You / Your</strong>" refers to the User
                      of Service, Website and the CC.
                    </p>

                    <p>
                      <strong>Dobzin Internet (OPC) Private Limited</strong> is
                      a private company registered under the Companies Act, 2013
                      having its registered office at Innov8, ILD Trade Tower,
                      Sector-47, Sohna Road, Gurugram, Haryana 122018, India
                      (hereinafter referred to as "<strong>Dobzin</strong>").
                    </p>

                    <p>
                      Dobzin is a registered trademark of Get Dobzin Internet
                      (OPC) Private Limited.
                    </p>

                    <h3>Definitions</h3>

                    <p>
                      "<strong>Applicable Law</strong>" shall mean any statute,
                      law, regulation, ordinance, rule, judgment, order, decree,
                      by-law, approval from the concerned authority, government
                      resolution, order, directive, guideline, policy,
                      requirement, or other governmental restriction or any
                      similar form of decision of, or determination by, or any
                      interpretation or adjudication having the force of law of
                      any of the foregoing, by any concerned authority having
                      jurisdiction over the matter in question;
                    </p>

                    <p>
                      "<strong>Service</strong>" shall mean technology platform
                      provided by Dobzin that allows Merchants to offer a
                      differentiated, hassle-free buying experience to eligible
                      Users including a tab offered by the Merchants to the
                      Users;
                    </p>

                    <p>
                      "<strong>Products</strong>" shall mean goods and /or
                      services offered by the Merchants on Merchant’s shop,
                      website, e-commerce website and mobile based application;
                    </p>

                    <p>
                      "<strong>User</strong>" shall mean any individual or
                      entity as approved by Dobzin;
                    </p>

                    <h3>Consent to accept terms of this agreement</h3>

                    <p>
                      By clicking on the tab/button/ checkbox of “Dobzin Buy” or
                      “Order with Dobzin” or any other button/checkbox of
                      similar nature, (i) you confirm that eligible under
                      Applicable Law to contract with Dobzin, (ii) you consent
                      to conduct transactions, accept the terms and conditions
                      of this Agreement and the Privacy Policy as displayed on
                      the Website and (iii) you consent to receive
                      communications, notices and information from us through
                      post or any other physical medium or electronically
                      (whether through SMS, emails, phone calls and automated
                      phone calls). Electronic communications shall be deemed to
                      have been received by you when we send the electronic
                      communication to the email address / mobile number /
                      details provided by You or any other third party during
                      the sign-up process as per our records, or when we post
                      the electronic communication on the Website.
                    </p>

                    <h3>The Service</h3>

                    <p>
                      Dobzin offers a technology platform on www.dobzin.in and
                      at merchant shop, website and mobile based application.
                    </p>

                    <p>
                      Dobzin’s technology platform enables Users to avail a tab
                      offered by third party merchants at their shops, websites
                      and mobile applications ("<strong>Merchant</strong>") for
                      transactions made with or through such Merchant.
                    </p>

                    <p>
                      Dobzin shall procure reasonable efforts to facilitate your
                      transaction with a Merchant in order to obtain Products,
                      subject to the availability of Products with the Merchant.
                    </p>

                    <p>
                      By using the Website, Service and/or the CC you hereby
                      acknowledge that Dobzin is not a Merchant. Dobzin only
                      facilitates the provision of a tab and a hassle-free
                      buying experience by the Merchant.
                    </p>

                    <p>
                      For the avoidance of any doubt, Dobzin itself does not
                      provide Products and Dobzin is not a provider of Products.
                      It is up to the Merchant to offer Products, which may be
                      requested through the Merchant’s shop, website or mobile
                      application. The provision of the Products by the Merchant
                      to you and any liability therefrom is therefore subject to
                      the agreement (to be) entered into between you and the
                      Merchant. Dobzin is not privy to such agreement.
                    </p>

                    <p>
                      Dobzin does not at any point of time during any
                      transaction between User and Merchant, take the ownership
                      of any of Products nor does it at any point assert any
                      rights or claims over the Products offered by Merchant to
                      User.
                    </p>

                    <p>
                      For enabling the Service, Dobzin may partner with one or
                      more banks, financial institutions or other entities ("
                      <strong>Financial Partner</strong>"). A part or whole of
                      the Service may be provided by or delegated to, the
                      Financial Partners. Further, the Service may also be
                      linked, transferred or assigned to products provided by
                      our Financial Partners and may reflect on your account or
                      profile with our Financial Partners. Any linking or
                      transfer to Financial Partners shall be made with your
                      consent. Further, in case of bankruptcy or our failure to
                      pay our creditors, our creditors shall have the rights to
                      claim any dues owned by you in accordance with Applicable
                      Law.
                    </p>

                    <p>
                      Dobzin shall collect and hold all documents, writings,
                      agreements, cheques, drafts, other instruments received
                      from the Users including without limitation, post-dated
                      cheques, demand promissory notes, correspondence and
                      records relating to the payments for the Products, in
                      trust and as agent for the Merchant, as the case may be.
                    </p>

                    <p>
                      Dobzin shall maintain necessary records in respect of the
                      transactions entered into by the User with the Merchants
                      and amounts due in respect of Products and the User agrees
                      to sharing of such records by Dobzin with the Financial
                      Partner or the Merchant in order to facilitate the
                      Service. The User agrees that such records as maintained
                      by Dobzin shall be sufficient proof of the transactions
                      entered into between the User and Merchants and the
                      amounts due thereto, which the User shall not dispute.
                    </p>

                    <p>
                      Dobzin reserves the right to change the nature of Services
                      from time to time without any prior notice.
                    </p>

                    <p>
                      User acknowledges and agrees that Dobzin may stop
                      (permanently or temporarily) providing the Services (or
                      any features within the Services) to you or to users
                      generally at Dobzin’s sole discretion, without prior
                      notice to you. You may stop using the Services at any
                      time, provided that amounts that are due from you to
                      Dobzin under the User terms shall be discharged by you.
                      You do not need to specifically inform Dobzin when you
                      stop using the Services.
                    </p>

                    <p>
                      The User acknowledges that each transaction shall be
                      assessed by Dobzin in accordance with its own internal
                      standards for processing of such transactions and Dobzin
                      shall have the right to deny the processing of any
                      transaction at its sole discretion.
                    </p>

                    <h3>User eligibility</h3>
                    <p>
                      Users as approved by Dobzin, shall have the right to use
                      the Service provided by Dobzin.
                    </p>

                    <p>
                      The Service is available only to User who can form legally
                      binding contracts under the Applicable Law.
                    </p>

                    <p>
                      User must not be a minor as per Applicable Law i.e. User
                      must be at least 18 years of age to be eligible to use our
                      Service.
                    </p>

                    <p>
                      Dobzin advises its Users that while accessing the Website,
                      Service or CC, they must follow and abide by the
                      Applicable Laws. Dobzin at all the times reserves the
                      right to deny the Service.
                    </p>

                    <h3>User accounts, offers and promotions</h3>

                    <p>
                      Dobzin collects general user data including name,
                      email-id, address, contact details etc. to facilitate
                      Services by creating an account of the User on the Website
                      in accordance with Applicable Laws. Dobzin also collects
                      relevant user data from the Merchants to facilitate the
                      Service efficiently. The collection, verification, audit
                      and maintenance of correct and updated User information is
                      a continuous process and Dobzin reserves the right, at any
                      time, to take steps necessary to ensure User’s compliance
                      with all relevant and applicable KYC requirements, if any.
                    </p>

                    <p>
                      It is assumed that all information provided by the User
                      for signing up on the Website is correct accurate and up
                      to date. Dobzin can verify the information that User have
                      provided and choose to refuse the Service or use of the
                      Website without providing reasons. Also, Dobzin reserves
                      the right to terminate its Services on account of misuse
                      and misrepresentation of any information provided by the
                      User will lead to automated termination of Service without
                      any prior notice to such User.
                    </p>

                    <p>
                      User account bearing details provided by the User are
                      created and owned by Dobzin. Any promotional discounts,
                      offers and reward points accumulated or likes of such
                      provided by the Merchants can be revoked without prior
                      notice in the event of suspicious account activity or
                      malafide intent/conduct of the User. In the case where the
                      system is unable to establish unique identity of the User
                      against the details provided to Dobzin, the account shall
                      be indefinitely suspended. Dobzin reserves the full
                      discretion to suspend a User’s account in the above event
                      and does not have the liability to share any account
                      information whatsoever.
                    </p>

                    <h3>Usage conditions</h3>

                    <p>
                      Users agree to use the Services only for purposes that are
                      permitted by a) the User Terms and b) any Applicable Laws
                      as amended from time to time for the time being in force.
                    </p>

                    <p>By using the Website You agree not to:</p>
                    <ul className="article-features-list">
                      <li>authorize others to use your account;</li>
                      <li>
                        assign or otherwise transfer Your account to any third
                        person or legal entity;
                      </li>
                      <li>
                        use the Service or Website for unlawful purposes,
                        including but not limited to sending or storing any
                        unlawful material or for fraudulent purposes;
                      </li>
                      <li>
                        use the Service or Website to cause nuisance, annoyance
                        or inconvenience;
                      </li>
                      <li>
                        use the Service or Website with an incompatible or
                        unauthorized device
                      </li>
                      <li>
                        impair the proper operation of the network and/or
                        interfere with or disrupt the integrity or performance
                        of the Website or Service;
                      </li>
                      <li>
                        reverse engineer or access the Service or Website in
                        order to design or build a competitive product or
                        service, design or build a product using similar ideas,
                        features, functions or graphics of the Website or copy
                        any ideas, features, functions or graphics of the
                        Website.
                      </li>
                      <li>
                        launch an automated program or script, including, but
                        not limited to, web spiders, web crawlers, web robots,
                        web ants, web indexers, bots, viruses or worms, or any
                        program which may make multiple server requests per
                        second, or unduly burdens or hinders the operation
                        and/or performance of the Website or Service;
                      </li>
                      <li>
                        try to harm the Service or Website in any way
                        whatsoever;
                      </li>
                      <li>
                        disclose information designated as confidential by
                        Dobzin, without Dobzin’s prior written consent; and
                      </li>
                      <li>
                        copy or distribute the Service or Website or other
                        Dobzin content without written permission from Dobzin.
                      </li>
                    </ul>
                    <p>Payment conditions</p>
                    <ul className="article-features-list">
                      <li>
                        While using the Service, the User by clicking on the
                        “Dobzin Checkout” button or any other similar button as
                        provided under the Service on the Merchant’s shop,
                        website, e-commerce website and mobile based
                        application, shall have effected a transaction whereby
                        the User agrees that the amounts due under such
                        transaction are in relation to goods or services availed
                        by the User from the Merchants and the same may be
                        recovered by Dobzin on behalf of the Merchant by Dobzin.
                        The User shall not contest to right of Dobzin to recover
                        such amounts on behalf of the Merchant. Upon payment of
                        such amounts to Dobzin, the User shall not have any
                        liability to the Merchant in respect of such amounts
                        paid to Dobzin.
                      </li>
                      <li>
                        User shall make payments for the purchases made via
                        Service in the following manner: a) For purchases made
                        between the 1st and 15th of a month, the payment will be
                        made by the 20th of that month or any later date as
                        maybe be intimated by Dobzin; and b) For purchases made
                        between the 16th and 30th of a month, the payment will
                        be made by the 5th of the following month or any later
                        date as maybe be intimated by Dobzin.
                      </li>
                      <li>
                        Dobzin or its representatives may notify (including by
                        means of post, emails, SMS, phone calls, automated phone
                        calls) the User at any time (including on and after the
                        due dates of payment) regarding the details of payments
                        due. User agrees to the sufficiency of such notification
                        and agrees to make the payments due forthwith upon such
                        notification.
                      </li>
                      <li>
                        User shall be entitled to make payments for the Products
                        purchased through NEFT, ECS/NACH and Debit Card payment
                        options. Users may also make payments through Credit
                        Cards by connecting with CC for enabling such payment
                        option.
                      </li>
                      <li>
                        The User shall be notified of the due date of payments
                        as per the provisions of this Agreement.
                      </li>
                      <li>
                        In the event of User not being provided notice of
                        non-payment of due for reasons attributable to the User
                        or the User not adhering to the provisions of Clause
                        6.3(b), Dobzin shall (i) impose a fine of up to Rs 500
                        (Rupees Five Hundred Only) + applicable taxes (GST,
                        etc.) per billing cycle on the User; (ii) be entitled to
                        gather information in accordance with Applicable Law
                        from third parties in respect of the User for the
                        purpose of collection of amounts due from the User;
                        (iii) be entitled to engage third party collection
                        agencies for the purpose of collection of amounts due
                        from the User and (iv) be entitled to report any
                        information relating to non-payment of amounts due from
                        the User to credit bureaus or any other person having
                        the authority to collect such information in accordance
                        with Applicable Law. Dobzin reserves the right to vary
                        such fine or impose any other fine in addition to or in
                        replacement thereof.
                      </li>
                      <li>
                        If the User does not pay the amounts due for a period of
                        30 days from the date such amounts are due, Dobzin may
                        suspend the usage of the account of the User at its
                        discretion and notify the Merchants regarding such
                        suspension of User’s account. User agrees to sharing of
                        such information by Dobzin to the Merchants. Dobzin may
                        revoke such suspension upon imposing any additional
                        terms and conditions on the User and such additional
                        terms and conditions shall be deemed to constitute a
                        part of the User Terms.
                      </li>
                      <li>
                        Dobzin reserves the rights to proceed against You in any
                        manner as Dobzin may deem fit (including but not limited
                        to any court process in a jurisdiction of Dobzin’s
                        choice) as per Applicable Law in relation to any amount
                        due to any Merchants.
                      </li>
                      <li>
                        User further agrees to:li>copy or distribute the Service
                        or Website or other Dobzin content without written
                        permission from Dobzin.
                      </li>
                    </ul>

                    <p>User further agrees to:</p>
                    <ul className="article-features-list">
                      <li>
                        have understood the contract and terms and conditions
                        laid therein with Dobzin for Website usage and you have
                        clearly understood the Service;
                      </li>
                      <li>
                        use the Services for personal purpose only (applicable
                        in case of individuals);
                      </li>
                      <li>
                        use an access point or 3G/4G data account which you are
                        authorized to use;
                      </li>
                      <li>
                        the business entity, organisations and body corporate
                        shall use the Services for authorised purpose only;
                      </li>
                      <li>
                        keep account information confidential or any other
                        identification provided by Dobzin which allows access to
                        the Service and the Website;
                      </li>
                      <li>
                        provide with proof of identity/address reasonably
                        requested by Dobzin;
                      </li>
                      <li>
                        comply with all Applicable Law while using the Website
                        and the Service; and
                      </li>
                      <li>
                        access or (attempt to access) any of the Services by any
                        means other than through the interface that is provided
                        by Dobzin.
                      </li>
                    </ul>

                    <p>
                      You are solely responsible for any breach of your
                      obligations under this agreement (including financial
                      obligations) and for the consequences (including any loss
                      or damage which Dobzin may suffer) of any such breach.
                    </p>

                    <p>
                      Dobzin reserves the right to immediately terminate the
                      Service and the use of the Website should you not comply
                      with any of the above rules.
                    </p>

                    <h3>Usage conditions</h3>

                    <p>
                      It is expected that a reasonable behaviour shall be
                      followed by the Users while utilizing the Services offered
                      by the Website and/or CC.
                    </p>

                    <p>
                      All the calls made to the Dobzin’s CC are recorded by
                      Dobzin for quality and training purposes.
                    </p>

                    <h3>Representation and warranties</h3>

                    <p>
                      Without prejudice to the above, Dobzin makes no
                      representation or warranty that:
                      <br />
                      The Services will meet the User’s requirements.
                    </p>

                    <p>
                      The Services will be uninterrupted, timely or error free.
                    </p>

                    <h3>Amendment to terms of contract</h3>

                    <p>
                      Dobzin reserves the right to add, vary or amend any or all
                      these terms and conditions at any time without prior
                      notice and the User shall be bound by such addition,
                      variation or amendment once such addition, variation or
                      amendment are incorporated into these User Terms at
                      Dobzin’s website at www.dobzin.in on the date that Dobzin
                      may indicate that such addition, variation or amendment is
                      to come into effect.
                    </p>

                    <h3>Intellectual property rights</h3>

                    <p>
                      Dobzin is the sole owner or lawful licensee of all the
                      rights to the Website and its content. Website content
                      means its design, layout, text, images, graphics, sound,
                      video etc. The website content embodies trade secrets and
                      intellectual property rights protected under worldwide
                      copyright and other Applicable Laws. All title, ownership
                      and intellectual property rights in the Website and its
                      content shall remain with Dobzin, its affiliates or
                      licensor’s of Dobzin content, as the case may be.
                    </p>

                    <p>
                      These User Terms do not constitute a sale and do not
                      convey to User any rights of ownership in or related to
                      the Website, or any intellectual property rights owned by
                      Dobzin.
                    </p>

                    <p>
                      All rights not otherwise claimed under this contract by
                      www.dobzin.in are hereby reserved. The information
                      contained in this Website is intended, solely to provide
                      general information for the personal use of the reader,
                      who accepts full responsibility for its use. Dobzin does
                      not represent or endorse the accuracy or reliability of
                      any information, or advertisements (collectively, the "
                      <strong>Content</strong>") contained on, distributed
                      through, or linked, downloaded or accessed from any of the
                      Services contained on this Website, or the quality of any
                      products, information or other materials displayed, or
                      obtained by you as a result of an advertisement or any
                      other information or offer in or in connection with the
                      Services provided through the online technology platform.
                      Dobzin reserves the right to make changes and corrections
                      to any part of the Content of this Website at any time
                      without prior notice.
                    </p>

                    <p>
                      We accept no responsibility for any errors or omissions,
                      or for the results obtained from the use of this
                      information. All information on this Website is provided
                      "as is" and "<strong>as available</strong>" with no
                      guarantee of completeness, accuracy, timeliness or of the
                      results obtained from the use of this information, and
                      without warranty of any kind, express or implied,
                      including, but not limited to warranties of performance,
                      merchantability and fitness for a particular purpose.
                      Nothing herein shall to any extent substitute for the
                      independent investigations and the sound technical and
                      business judgment of the User(s). In no event shall Dobzin
                      be liable for any direct, indirect, incidental, punitive,
                      or consequential damages of any kind whatsoever with
                      respect to the Service. User(s) of this Website must
                      hereby acknowledge that any reliance upon any content
                      shall be at their sole risk. Dobzin reserves the right
                      (but shall have no obligation) to pre-screen, review,
                      flag, filter, modify, refuse or remove any or all Content
                      from any Service. It reserves the right to moderate,
                      publish, re-publish, and use all user generated data,
                      contributions and comments (including but not limited to
                      reviews, comments, likes, favorites, votes) posted on the
                      website as it deems appropriate (whether in whole or in
                      part) for its product(s), whether owned or affiliated. It
                      is not liable to pay royalty to any user for re-publishing
                      any content across any of its platforms.
                    </p>

                    <p>
                      All rights not otherwise claimed under this contract by
                      www.dobzin.in are hereby reserved. The information
                      contained in this Website is intended, solely to provide
                      general information for the personal use of the reader,
                      who accepts full responsibility for its use. Dobzin does
                      not represent or endorse the accuracy or reliability of
                      any information, or advertisements (collectively, the "
                      <strong>Content</strong>") contained on, distributed
                      through, or linked, downloaded or accessed from any of the
                      Services contained on this Website, or the quality of any
                      products, information or other materials displayed, or
                      obtained by you as a result of an advertisement or any
                      other information or offer in or in connection with the
                      Services provided through the online technology platform.
                      Dobzin reserves the right to make changes and corrections
                      to any part of the Content of this Website at any time
                      without prior notice.
                    </p>

                    <p>
                      Dobzin reserves the right, in its sole discretion and
                      without any obligation, to make improvements to, or
                      correct any error or omissions in any portion of the
                      Services or the Website.
                    </p>

                    <h3>Trademark</h3>
                    <p>
                      All related icons and logos are registered trademarks or
                      service marks of Dobzin in various jurisdictions and are
                      protected under applicable copyright, trademark and other
                      proprietary rights Applicable Laws. The unauthorized
                      copying, modification, use or publication of these marks
                      is strictly prohibited.
                    </p>

                    <h3>Copyright</h3>

                    <p>
                      All content on the Website and Service is the copyright of
                      Dobzin except the third party content and any link to
                      third party website on our Website.
                    </p>

                    <p>
                      Any systematic retrieval of Dobzin content to create or
                      compile, directly or indirectly, a collection,
                      compilation, database or directory (whether through
                      robots, spiders, automatic devices or manual processes)
                      without written permission from Dobzin is prohibited.
                    </p>

                    <p>
                      In addition, use of the content for any purpose not
                      expressly permitted in this agreement is prohibited and
                      may invite legal action. As a condition of Your access to
                      and use of Dobzin’s Services, You agree that You will not
                      use the Website and/or Service to infringe the
                      intellectual property rights of others in any way. Dobzin
                      reserves the right to terminate the account of a User(s)
                      upon any infringement of the rights of others in
                      conjunction with use of Dobzin’s Service, or if Dobzin
                      believes that User’s conduct is harmful to the interests
                      of Dobzin, its affiliates, or other Users, or for any
                      other reason in Dobzin’s sole discretion, with or without
                      cause.
                    </p>

                    <h3>Arrangement between you and the issuing bank</h3>

                    <p>
                      All valid credit / debit/ cash card/ and other payment
                      instruments are processed using a credit card payment
                      gateway or appropriate payment system infrastructure and
                      the same will also be governed by the terms and conditions
                      agreed to between You and the respective issuing bank and
                      payment instrument issuing company.
                    </p>

                    <p>
                      All online bank transfers from valid bank accounts are
                      processed using the gateway provided by the respective
                      issuing bank which support payment facility to provide
                      these services to You. All such online bank transfers on
                      payment facility are also governed by the terms and
                      conditions agreed to between You and the respective
                      issuing bank.
                    </p>

                    <h3>Indemnification and limitation of liability</h3>
                    <p>
                      Dobzin shall not be responsible or liable for any loss or
                      damage, howsoever caused or suffered by the User arising
                      out of the use Products offered by Merchant or due to the
                      failure of Merchant to provide Product to the Users for
                      any reason whatsoever including but not limited to the
                      User’s noncompliance with the Service’s terms,
                      malfunction, partial or total failure of any network
                      terminal, data processing system, computer telecom
                      transmission or telecommunications system or other
                      circumstances whether or not beyond the control of Dobzin
                      or any person or any organization involved in the above
                      mentioned systems.
                    </p>

                    <p>
                      Dobzin will not be liable for any damages of any kind
                      arising from the use of the Products offered by the
                      Merchant including, but not limited to direct, indirect,
                      incidental, punitive, and consequential damages.
                    </p>

                    <p>
                      Dobzin shall not be liable for any Content that you may
                      find indecent, offensive or objectionable. You shall use
                      the Services at your own risk.
                    </p>

                    <p>
                      Dobzin will take all reasonable measures to ensure that
                      Merchant should fulfill his duty properly but there may be
                      exceptions and therefore Dobzin will not be held liable
                      for any such compensation on account of the Merchant not
                      meeting expectations of Users.
                    </p>

                    <p>
                      Dobzin shall not be liable for any conduct of the Merchant
                      or the Financial Partner. Dobzin encourages Users to
                      notify any complaints that User may have against any
                      Merchant that User may have.
                    </p>

                    <p>
                      No advice or information, whether oral or written,
                      obtained by you from Dobzin or through or from the
                      services shall create any warranty not expressly stated in
                      the terms.
                    </p>

                    <p>
                      Dobzin disclaims any and all liability in respect of the
                      Merchant and their Products provided thereof.
                    </p>

                    <p>
                      User agrees to indemnify and keep Dobzin, its affiliates
                      and licensors indemnified against all costs, expenses,
                      damages, losses and liabilities incurred or suffered by
                      Dobzin or its affiliated companies related to any User
                      content posted or transmitted by User during the use of
                      the Website or Service or any unauthorised use of the
                      Website or Service in contravention of this Agreement.
                    </p>

                    <h3>Governing law and dispute resolution</h3>

                    <p>
                      These User Terms shall be governed by, and construed in
                      accordance with, the laws of India, without reference to
                      principles of conflicts of law. The parties agree that the
                      courts of Mumbai shall have exclusive jurisdiction over
                      any dispute arising from or relating to the User Terms
                      and/or the Website.
                    </p>

                    <p>
                      You expressly consent to the personal jurisdiction of said
                      courts and waive any objection to such personal
                      jurisdiction based on forums non convenience or any other
                      basis.
                    </p>

                    <footer className="footer-area">
                      <div className="container">
                        <div className="row">
                          <div className="col-lg-3 col-sm-6 col-md-6">
                            <div className="single-footer-widget">
                              <div className="logo">
                                <NavLink to="/">
                                  <img
                                    src="assets/media/black-logo.png"
                                    alt="logo"
                                  />
                                </NavLink>
                                <p>
                                  Dobzin is a digital payment solution to
                                  provide app based credit line.
                                </p>
                              </div>
                              <ul className="social-links">
                                <li>
                                  <a
                                    href="https://www.facebook.com/dobzinindia"
                                    target="_blank"
                                  >
                                    <i className="fab fa-facebook-f"></i>
                                  </a>
                                </li>
                                <li>
                                  <a
                                    href="https://twitter.com/dobzinindia"
                                    target="_blank"
                                  >
                                    <i className="fab fa-twitter"></i>
                                  </a>
                                </li>
                                <li>
                                  <a
                                    href="https://www.instagram.com/dobzin/"
                                    target="_blank"
                                  >
                                    <i className="fab fa-instagram"></i>
                                  </a>
                                </li>
                                <li>
                                  <a
                                    href="https://www.linkedin.com/company/dobzin"
                                    target="_blank"
                                  >
                                    <i className="fab fa-linkedin-in"></i>
                                  </a>
                                </li>
                              </ul>
                            </div>
                          </div>
                          <div className="col-lg-3 col-sm-6 col-md-6">
                            <div className="single-footer-widget pl-5">
                              <h3>Company</h3>
                              <NavList />
                            </div>
                          </div>
                          <div className="col-lg-3 col-sm-6 col-md-6">
                            <div className="single-footer-widget">
                              <h3>Quick Links</h3>
                              <QuickLinks />
                            </div>
                          </div>
                          <div className="col-lg-3 col-sm-6 col-md-6">
                            <div className="single-footer-widget">
                              <h3>Address</h3>
                              <ul className="footer-contact-info">
                                <li>
                                  <span> Location :</span> Innov8, ILD Trade
                                  Tower, Sector-47, Sohna Road, Gurugram,
                                  Haryana 122018
                                </li>
                                <li>
                                  <span>Email :</span>{" "}
                                  <a href="mailto:support@dobzin.in">
                                    support@dobzin.in
                                  </a>
                                </li>
                                <li>
                                  <span>Call Us :</span> <a>+91 9015355470</a>
                                </li>
                              </ul>
                            </div>
                          </div>
                        </div>
                        <div className="copyright-area">
                          <p>
                            Copyright @2020 <a> DOBZIN</a>. All rights reserved
                          </p>
                        </div>
                      </div>
                      <div className="map-image">
                        <img src="assets/media/map.png" alt="map" />
                      </div>
                    </footer>

                    <div className="go-top">
                      <i className="fas fa-arrow-up" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    );
  }
}
